# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modelrepairman.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ModelRepairman(object):
    def setupUi(self, ModelRepairman):
        ModelRepairman.setObjectName("ModelRepairman")
        ModelRepairman.resize(1066, 575)
        self.gridLayout_2 = QtWidgets.QGridLayout(ModelRepairman)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(ModelRepairman)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(ModelRepairman)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 3)
        self.tno_lineEdit = QtWidgets.QLineEdit(ModelRepairman)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tno_lineEdit.sizePolicy().hasHeightForWidth())
        self.tno_lineEdit.setSizePolicy(sizePolicy)
        self.tno_lineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.tno_lineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tno_lineEdit.setFont(font)
        self.tno_lineEdit.setObjectName("tno_lineEdit")
        self.gridLayout.addWidget(self.tno_lineEdit, 4, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(ModelRepairman)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 1, 1, 1)
        self.N_label = QtWidgets.QLabel(ModelRepairman)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.N_label.setFont(font)
        self.N_label.setObjectName("N_label")
        self.gridLayout.addWidget(self.N_label, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 6, 4, 1, 1)
        self.n_lineEdit = QtWidgets.QLineEdit(ModelRepairman)
        self.n_lineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_lineEdit.sizePolicy().hasHeightForWidth())
        self.n_lineEdit.setSizePolicy(sizePolicy)
        self.n_lineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.n_lineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.n_lineEdit.setFont(font)
        self.n_lineEdit.setObjectName("n_lineEdit")
        self.gridLayout.addWidget(self.n_lineEdit, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(ModelRepairman)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 3, 1, 1)
        self.calculateButton = QtWidgets.QPushButton(ModelRepairman)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calculateButton.sizePolicy().hasHeightForWidth())
        self.calculateButton.setSizePolicy(sizePolicy)
        self.calculateButton.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.calculateButton.setFont(font)
        self.calculateButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.calculateButton.setObjectName("calculateButton")
        self.gridLayout.addWidget(self.calculateButton, 6, 2, 1, 2)
        self.label_7 = QtWidgets.QLabel(ModelRepairman)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 5, 1, 2)
        self.to_lineEdit = QtWidgets.QLineEdit(ModelRepairman)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_lineEdit.sizePolicy().hasHeightForWidth())
        self.to_lineEdit.setSizePolicy(sizePolicy)
        self.to_lineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.to_lineEdit.setFont(font)
        self.to_lineEdit.setObjectName("to_lineEdit")
        self.gridLayout.addWidget(self.to_lineEdit, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(ModelRepairman)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(ModelRepairman)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(22, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout.addItem(spacerItem1, 7, 4, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(ModelRepairman)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget, 3, 5, 5, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)

        self.retranslateUi(ModelRepairman)
        QtCore.QMetaObject.connectSlotsByName(ModelRepairman)

    def retranslateUi(self, ModelRepairman):
        _translate = QtCore.QCoreApplication.translate
        ModelRepairman.setWindowTitle(_translate("ModelRepairman", "Dialog"))
        self.label_5.setText(_translate("ModelRepairman", "ч."))
        self.label_4.setText(_translate("ModelRepairman", "Исходные данные"))
        self.tno_lineEdit.setText(_translate("ModelRepairman", "1000"))
        self.label_3.setToolTip(_translate("ModelRepairman", "<html><head/><body><p>Среднее время ремонта одного компьютера</p></body></html>"))
        self.label_3.setText(_translate("ModelRepairman", "tо"))
        self.N_label.setToolTip(_translate("ModelRepairman", "<html><head/><body><p>Количество компьютеров</p></body></html>"))
        self.N_label.setText(_translate("ModelRepairman", "N"))
        self.n_lineEdit.setToolTip(_translate("ModelRepairman", "<html><head/><body><p><br/></p></body></html>"))
        self.n_lineEdit.setWhatsThis(_translate("ModelRepairman", "<html><head/><body><p><br/></p></body></html>"))
        self.n_lineEdit.setText(_translate("ModelRepairman", "10"))
        self.label.setText(_translate("ModelRepairman", "шт."))
        self.calculateButton.setText(_translate("ModelRepairman", "Рассчитать"))
        self.label_7.setText(_translate("ModelRepairman", "Результаты"))
        self.to_lineEdit.setText(_translate("ModelRepairman", "10"))
        self.label_2.setToolTip(_translate("ModelRepairman", "<html><head/><body><p>Среднее время наработки на отказ одного компьютера</p></body></html>"))
        self.label_2.setText(_translate("ModelRepairman", "tно"))
        self.label_6.setText(_translate("ModelRepairman", "ч."))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ModelRepairman", "Параметр"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ModelRepairman", "Вариант 1"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ModelRepairman", "Вариант 2"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ModelRepairman", "Вариант 3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ModelRepairman = QtWidgets.QDialog()
    ui = Ui_ModelRepairman()
    ui.setupUi(ModelRepairman)
    ModelRepairman.show()
    sys.exit(app.exec_())

